Openseadragon
in-depth/indepth-demo pull request #42
Opened 2016-10-17 02:32 UTC by gerardmrk

Working example, no easier alternative atm other than uploading high-res image to the repo.

2016-10-17 11:26 UTC, ro-savage requested changes
Awesome work Gerard. You got it working damn quickly!

So there a few things that I dont understand and would like to know more about. And a couple suggestion on how to simplify code / come in line with our coding stytle.

A few issues too:
- [ ] `npm run ssr-start` is broken because our server doesnt understand 

``` js
 7 |
   8 | class DeepZoom extends Component {
>  9 |   static propTypes = {
     |                    ^
  10 |     url: PropTypes.string.isRequired,
  11 |   }
```
- [ ] The server side rendering also breaks because openseadragon wants to access `window` which doesn't exist.
- [ ] Has this been tested on android and iphone?
- [ ] I can't drag to move around the image when zoomed?
- [ ] Lets leave in the original deepzoom for now, because they are real deep zooms and implement this deepzoom on the maps page.

Let's see if we can get it working using cloudinary hosted files. But this can be a separate PR.

Again, awesome work Gerard!

2016-10-17 11:26 UTC, ro-savage commented on src/shared/views/plugins/DeepZoom/DeepZoom.js
> +import React, { Component, PropTypes } from 'react'
We just import `React` then use `React.Component` & `React.PropTypes`.

Its really just a personal preference, but we have standardized on that.

2016-10-17 11:26 UTC, ro-savage commented on src/shared/views/plugins/DeepZoom/DeepZoom.js
> +  static propTypes = {
Again, we are using `DeepZoom.propTypes = {}`.
Personal preference, but let's keep it consistent in this codebase.

2016-10-17 11:26 UTC, ro-savage commented on src/shared/views/plugins/DeepZoom/DeepZoom.js
>  export default DeepZoom
I would simplify this component.

 Maybe I am missing something and there is a part I dont understand?

Wanna chat on slack about it @gerardmrk ?

```js
import React from 'react'
import OpenSeaDragon from 'openseadragon'

import styles from './DeepZoom.css'

const DeepZoom = (props) => {
  const mountOpenSeaDragon = (el, url) => {
    OpenSeaDragon({
      element: el,
      prefixUrl: '/static/images/dzi-controls/',
      tileSources: url,
      maxZoomPixelRatio: Infinity,
    })
  }

  return (
    <div
      ref={el => { mountOpenSeaDragon(el, props.url) }}
      className={styles.holder}
    />
  )
}

DeepZoom.propTypes = {
  url: React.PropTypes.string.isRequired,
}

export default DeepZoom
```

2016-10-17 11:26 UTC, ro-savage commented on converttodzi.js
> +/* eslint-disable */
Does this file create a .dzi but searching every file/folder in `image/scollection-item` ?
Or does it actually cut up the images too?

2016-10-17 11:26 UTC, ro-savage commented on src/static/images/collection-items/aircraft-carrier.dzi
> +<?xml version="1.0" encoding="UTF-8"?>
I don't understand how the dzi file knows where too look?

2016-10-17 21:09 UTC, gerardmrk commented on converttodzi.js
> +/* eslint-disable */
It uses sharp to convert any compatible image files it finds in the `collection-items` directory to dzi. It generates their respective tiles too, you can find them in folders named after the original files and postfixed with `_files`. If you open the network tab in Chrome dev tools, you'll see that it successfully calls the appropriate tiles with status 200 everytime you zoom-in. I had to use a high-res image to properly show proof-of-concept; the original images (the aircraft carrier for example) weren't high-res enough that Nick and I initially thought it wasn't calling the right tiles etc.

2016-10-17 21:14 UTC, gerardmrk commented on src/static/images/collection-items/aircraft-carrier.dzi
> +<?xml version="1.0" encoding="UTF-8"?>
the dzi file itself is actually an XML file, not an image file. Had to do bit of reading bout it too to realize that's how it's supposed to work. You can open the file in Atom (it won't crash) and actually see the XML attributes. After the client calls the `.dzi` file, it immediately looks into the same location (i.e. `/static/images/collection-items/..`) for the tiles. and renders them accordingly.

2016-10-17 21:16 UTC, gerardmrk commented on converttodzi.js
> +/* eslint-disable */
Sharp is Node.js's image-processing tool. All it's dependencies are statically-linked, so you won't have to worry bout `brew install imagemagick` or `libdv` etc, it auto-installs and keeps it in node_modules. This was just a temporary setup so we can use this to immediately convert images we want to dzi. Sharp is faster than all image-processing packages out there for node (of the few that exists) and apparently even more performant than graphicsmagick and imagemagick in certain scenarios. that's why I chose it. It's also currently the only package that has all its dependencies statically linked so completely portable.

2016-10-21 10:42 UTC, ro-savage approved these changes

2016-10-21 10:42 UTC, ro-savage commented on webpack.universal.js
> +      IMAGE_STORAGE_URL: JSON.stringify(process.env.IMAGE_STORAGE_URL),
Seems weird to pass as a var to webpack. In fact is weird. We should just a config while in the app itself.

But works for now.

2016-10-21 10:42 UTC, ro-savage commented on src/shared/views/plugins/DeepZoom/osd.js
> +import React from 'react'
Nice work. All working smoothly. Lets take a look at this in more detail when I am back.

Ace work getting it work. It rocks!

2016-10-21 10:42 UTC, ro-savage commented on src/shared/views/map/MapTab/MapTab.js
>  import React from 'react'
Awesome nice work again. I would say eventually we'll take this out and make it generic and then use it on the map page.

That way we get to use the controls you created everywhere.

Look and works really nicely!

2016-10-21 10:43 UTC, ro-savage commented
Awesome work gerard!! Approved and merged.

2016-10-21 10:43 UTC, merged